version: "3.1"

services:
  database:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    expose:
      - "5432:5432"
    environment:
      POSTGRES_DB: cron
      POSTGRES_USER: cron
      POSTGRES_PASSWORD: cron
    command: [ "docker-entrypoint.sh", "-c", "wal_level=logical", "-c", "max_connections=300" ]

  cron-1:
    image: debian:stable-slim
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY="DwawKTG44CItXXGuVVW3zDCZHqxUzh8tYMAJ7p3Tpt8="
      - ROCKET_DATABASES={questions={url="postgres://cron:cron@database/cron"}}
    volumes:
      - ./target/x86_64-unknown-linux-musl/release/q-api-cron:/usr/bin/q-api-cron
    command: ["q-api-cron"]
    depends_on: ["database"]
    deploy:
      replicas: 1
    ports:
      - "8001:8000"

  cron-2:
    image: debian:stable-slim
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY="DwawKTG44CItXXGuVVW3zDCZHqxUzh8tYMAJ7p3Tpt8="
      - ROCKET_DATABASES={questions={url="postgres://cron:cron@database/cron"}}
    volumes:
      - ./target/x86_64-unknown-linux-musl/release/q-api-cron:/usr/bin/q-api-cron
    command: ["q-api-cron"]
    depends_on: ["cron-1"]
    # ports:
    #   - "8002:8000"
    deploy:
      replicas: 10
