
# {{{ health checkers
### profiles - users - auth
GET http://localhost:8001/health

GET http://localhost:8002/health

GET http://localhost:8003/health

### fmc
GET http://localhost:8005/health

### questions - answers
GET http://localhost:8011/health

GET http://localhost:8012/health

### modules
GET http://localhost:8021/health

### resources - papers
GET http://localhost:8031/health

GET http://localhost:8032/health

### local
GET http://localhost:8000/health
# }}}

### auth bypass
GET http://localhost:8003/auth/bypass/1
Accept: application/json

# {{{ cron

GET http://localhost:8000/api/v1/cron/1
Accept: application/json
Authorization: Bearer 
Content-type: application/json

POST http://localhost:8000/api/v1/cron/
Accept: application/json
Authorization: Bearer 
Content-type: application/json

{
  "service": "question",
  "route": "1",
  "job": {
    "schedule": "0/10 * * * * *",
    "since": "2023-10-04T11:13:00.0+0200",
    "until": "2023-10-04T11:30:30+0200"
  }
}

# "schedule": "0/10 * * * * *"

GET http://localhost:8000/api/v1/cron/7
Accept: application/json
Authorization: Bearer 
Content-type: application/json

DELETE http://localhost:8000/api/v1/cron/2
Accept: application/json
Authorization: Bearer 
Content-type: application/json

# }}}
