CREATE TABLE IF NOT EXISTS cronjobs ();

ALTER TABLE cronjobs
  ADD COLUMN id UUID PRIMARY KEY NOT NULL,
  ADD COLUMN schedule VARCHAR(20) NOT NULL,
  ADD COLUMN service  VARCHAR(20) NOT NULL,
  ADD COLUMN status   VARCHAR(20) NOT NULL,
  ADD COLUMN route    VARCHAR(60) NOT NULL,
  ADD COLUMN since    TIMESTAMP WITH TIME ZONE,
  ADD COLUMN until    TIMESTAMP WITH TIME ZONE;
